services:
  postgres:
    image: postgres:16-alpine
    container_name: pat-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: patdb
      POSTGRES_USER: pat
      POSTGRES_PASSWORD: pat
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pat -d patdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: pat-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10


volumes:
  postgres_data:
  pat_sqlite_data: